spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/frame2_local
    driver-class-name: com.mysql.jdbc.Driver